onboarding = false

[theme]
name = "one-dark"
auto_switch = false

[ui]
prompt_new_tab_name = false
status_indicators = "dots"
accent = "#ff6600"

[ui.toast]
delivery = "herdr"

[keys]
prefix = "ctrl+a"
navigate_workspace_up = "k"
navigate_workspace_down = "j"
split_vertical = "prefix+\\"

# HERDR + nvim integration
focus_pane_left = ""
focus_pane_down = ""
focus_pane_up = ""
focus_pane_right = ""

[[keys.command]]
key = "ctrl+h"
type = "plugin_action"
command = "local.vim-navigator.left"
description = "Vim-aware pane left"

[[keys.command]]
key = "ctrl+j"
type = "plugin_action"
command = "local.vim-navigator.down"
description = "Vim-aware pane down"

[[keys.command]]
key = "ctrl+k"
type = "plugin_action"
command = "local.vim-navigator.up"
description = "Vim-aware pane up"

[[keys.command]]
key = "ctrl+l"
type = "plugin_action"
command = "local.vim-navigator.right"
description = "Vim-aware pane right"
