#!/bin/bash

# Set source directory
SRC=~/.dotfiles

# Pull changes
echo "Pulling changes"
cd "$SRC" || exit
git pull

# List of config directories/files to copy
CONFIG_ITEMS=(
  ghostty
  nvim
  hypr
  waybar
  starship
)

echo "COPYING DOTFILES TO .config..."

# Copy each config directory
for item in "${CONFIG_ITEMS[@]}"; do
  cp -r "$SRC/$item" "$HOME/.config/"
done

# Copy .bashrc separately
cp -r "$SRC/.bashrc" "$HOME"
cp -r "$SRC/.bash_profile" "$HOME"
